name: hockeydb-dev
services:
  django:
    container_name: hockeydb-django
    build: ./django
    environment:
      HOCKEYDB_BUILD_MODE: "DEV"
    ports:
      - 8000:8000
    networks:
      - hockeydb

networks:
  hockeydb:
