name: hockeydb-dev
services:
  django:
    container_name: hockeydb-django
    build: ./django
    environment:
      HOCKEYDB_BUILD_MODE: "DEV"
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./data/db.sqlite3
        target: /db.sqlite3
    networks:
      - hockeydb

networks:
  hockeydb:
