name: hockeydb-dev
services:
  django:
    container_name: hockeydb-django
    build: ./django-app
    environment:
      HOCKEYDB_BUILD_MODE: "DEV"
    expose:
      - 8000
    networks:
      - hockeydb
  nginx:
    container_name: hockeydb-nginx
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - django
    networks:
      - hockeydb

networks:
  hockeydb:
