name: hockeydb-prod
services:
  django:
    container_name: hockeydb-django
    build: ./django
    environment:
      HOCKEYDB_BUILD_MODE: "PROD"
      HOCKEYDB_DB_USERNAME: "hockeydb"   # Don't use this in production!
      HOCKEYDB_DB_PASSWORD: "insecure!"  # Don't use this in production!
    expose:
      - 8000
    depends_on:
      - mysql
    networks:
      - hockeydb

  nginx:
    container_name: hockeydb-nginx
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - django
    networks:
      - hockeydb
  mysql:
    container_name: hockeydb-mysql
    build: ./mysql
    environment:
      MYSQL_DATABASE: "hockeydb"
      MYSQL_USER: "hockeydb"              # Don't use this in production!
      MYSQL_PASSWORD: "insecure!"         # Don't use this in production!
      MYSQL_ROOT_PASSWORD: "insecure!"    # Don't use this in production!
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - hockeydb

networks:
  hockeydb:
